"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import dotenv
from pathlib import Path
from datetime import timedelta
from django.utils.translation import gettext_lazy as _

dotenv.load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
dotenv.load_dotenv()
IS_DEBUG = os.getenv("IS_DEBUG", "1")

# '''' .ENV ''''
SECRET_KEY_DJ = os.getenv("SECRET_KEY_DJ", "")
DJANGO_SETTINGS_MODULE = os.getenv("DJANGO_SETTINGS_MODULE", "")

# APP
APP_PROTOCOL = os.getenv("APP_PROTOCOL", "")
APP_HOST = os.getenv("APP_HOST", "")
APP_HOST_REMOTE = os.getenv("APP_HOST_REMOTE", "")
APP_PORT = os.getenv("APP_PORT", "")
APP_PORT_AI = os.getenv("APP_PORT_AI", "")
APP_TIME_ZONE = os.getenv("APP_TIME_ZONE", "")

# db production
POSTGRES_DB = os.getenv("POSTGRES_DB", "")
POSTGRES_USER = os.getenv("POSTGRES_USER", "")
POSTGRES_HOST = os.getenv("POSTGRES_HOST", "")

POSTGRES_PORT = os.getenv("POSTGRES_PORT", "")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD", "")
DB_ENGINE = os.getenv("DB_ENGINE", "")

# db development
DATABASE_ENGINE_LOCAL = os.getenv("DATABASE_ENGINE_LOCAL", "")
DATABASE_LOCAL = os.getenv("DATABASE_LOCAL", "")

# jwt
JWT_ACCESS_TOKEN_LIFETIME_MINUTES = os.getenv("JWT_ACCESS_TOKEN_LIFETIME_MINUTES", 5)
JWT_REFRESH_TOKEN_LIFETIME_DAYS = os.getenv("JWT_REFRESH_TOKEN_LIFETIME_DAYS", 1)

# Email Service
SMTP_HOST=os.getenv("SMTP_HOST", "")
SMTP_USER=os.getenv("SMTP_USER", "")
SMTP_PORT=os.getenv("SMTP_PORT", "465")
SMTP_PASS=os.getenv("SMTP_PASS", "")

# Redis
REDIS_HOST=os.getenv("REDIS_HOST", "")
DB_TO_RADIS_PORT=os.getenv("DB_TO_RADIS_PORT", "")
DB_TO_RADIS_HOST=os.getenv("DB_TO_RADIS_HOST", "")
DB_TO_RADIS_CACHE_USERS=os.getenv("DB_TO_RADIS_CACHE_USERS", "")
# '''Cookie'''
SESSION_COOKIE_HTTPONLY = False  # CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True # change to the True - CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = "Lax"  # CSRF_COOKIE_SAMESITE = 'Lax'  # or 'Strict'
SESSION_COOKIE_AGE = 86400
# ''' CHOICES '''
AUTHENTIFICATION_STATUS = [
    ("-------", _("-------")),  # Value by default
    ("PROCESS", _("Beginning of authentification")),
    ("ERROR", _("Mistake to the authentification")),
    ("COMPLETED", _("Completed of authentification")),
]

DJANGO_ENV = os.environ.get('DJANGO_ENV')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = SECRET_KEY_DJ
if not SECRET_KEY:
    raise ValueError("SECRET_KEY must be set in environment variables")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if isinstance(IS_DEBUG, str) and int(IS_DEBUG) == 1 else False

# """" HOST """"
def get_allowed_hosts(allowed_hosts: str):
    """
    The function is for the securite connection to the allowed hosts
    """
    from django.core.exceptions import ImproperlyConfigured
    hosts = allowed_hosts.split(", ")
    hosts = [h.strip() for h in hosts if h.strip()]

    if DJANGO_ENV == 'production':
        hosts = [f"{APP_HOST_REMOTE}".strip(), '0.0.0.0', "db",
                 "backend",
                 "nginx",
                 "celery",
                 "redis", '[::1]']

    if not hosts and DJANGO_ENV == 'production':
        raise ImproperlyConfigured("ALLOWED_HOSTS must be set in production")
    return hosts

ALLOWED_HOSTS = get_allowed_hosts("127.0.0.1, localhost")
# """" DATABASE """"
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": f"{DB_ENGINE}",
        "NAME": f"{POSTGRES_DB}",
        "USER": f"{POSTGRES_USER}",
        "PASSWORD": f"{POSTGRES_PASSWORD}",
        "HOST": f"{POSTGRES_HOST}",
        "PORT": f"{POSTGRES_PORT}",
        "KEY_PREFIX": "person_",
    }
}
# POSTGRES DB TEST
if not DEBUG and DJANGO_ENV == 'testing':
    DATABASES['default']['NAME'] = os.getenv('TEST_DB_NAME', 'test_myapp_db')
    DATABASES['default']['USER'] = os.getenv('TEST_DB_USER', 'test_user')
    DATABASES['default']['PASSWORD'] = os.getenv('TEST_DB_PASSWORD', 'test_password')

# DEBUG
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'http')
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
if DEBUG:
    SECURE_BROWSER_XSS_FILTER = False
    SECURE_CONTENT_TYPE_NOSNIFF = False
    SECURE_SSL_REDIRECT = False # http is False & https is True
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_CROSS_ORIGIN_OPENER_POLICY = None
    WHITENOISE_MAX_AGE = 0
    WHITENOISE_USE_FINDERS = False
    # SQLite DB TEST
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "person_db.sqlite3"
    }
    # SQLite DB TEST
    if DJANGO_ENV.startswith("testing"):
        DATABASES["default"]["NAME"] =  BASE_DIR / "person_test_db.sqlite3"



INSTALLED_APPS = [
    "daphne",
    'wagtail.contrib.forms',
    'wagtail.contrib.redirects',
    'wagtail.embeds',
    'wagtail.sites',
    'wagtail.users',
    'wagtail.snippets',
    'wagtail.documents',
    'wagtail.images',
    'wagtail.search',
    'wagtail.admin',
    'wagtail.contrib.settings',
    'wagtail',
    'taggit',
    'modelcluster',
    'rest_framework',
    'corsheaders',
    'adrf',
    'channels',
    "webpack_loader",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'person'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    "django.middleware.csrf.CsrfViewMiddleware",
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, "templates"),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = "project.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/


LANGUAGE_CODE = "ru"

TIME_ZONE = f"{APP_TIME_ZONE.strip()}"

USE_I18N = True

USE_TZ = True

DATE_FORMAT = 'd.m.Y'
DATETIME_FORMAT = 'd.m.Y H:i'
USE_L10N = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,  "static"),
]
STATIC_ROOT = os.path.join(BASE_DIR,  "collectstatic/")
STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type

# Application definition
#file extension
f_extension = 'csv, docx, pdf,  rtf, txt, xlsx, zip'
WAGTAILDOCS_EXTENSIONS = list(f_extension.split(", "))# ['csv', 'docx', 'key', 'odt', 'pdf', 'pptx', 'rtf', 'txt', 'xlsx', 'zip']

# Options for file's repository/source
DEFAULT_FILE_STORAGE = 'django.core.files.storage.FileSystemStorage'

# '''WHITENOISE'''
# for a static files in production
# https://whitenoise.readthedocs.io/en/stable/django.html
WHITENOISE_MAX_AGE = 31536000  # static cache by 1 year
WHITENOISE_USE_FINDERS = True




# HASH passwords
# https://docs.djangoproject.com/en/4.2/topics/auth/passwords/
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.BCryptPasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
    "django.contrib.auth.hashers.MD5PasswordHasher",
]


# '''CORS'''
# False - this value is default and it's means what the server don't accept from other sources.
CORS_ORIGIN_ALLOW_ALL = True
# Here, we allow the URL list for publicated
CORS_ALLOWED_ORIGINS = [
    "http://0.0.0.0:8000",
    f"http://{DB_TO_RADIS_HOST}:{APP_PORT}",
    f"http://{DB_TO_RADIS_HOST}:{DB_TO_RADIS_PORT}",
    "http://127.0.0.1:8000",

]

# https://github.com/adamchainz/django-cors-headers?tab=readme-ov-file#csrf-integration
# https://docs.djangoproject.com/en/5.2/ref/settings/#std-setting-CSRF_TRUSTED_ORIGINS
# This is list from private of URL
CSRF_TRUSTED_ORIGINS = [*CORS_ALLOWED_ORIGINS]
# Allow the cookie in HTTP request.
CORS_ALLOW_CREDENTIALS = True
# Allow the methods to the methods in HTTP
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "Authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "Accept-Language",
    "Content-Language",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models_person.BigAutoField"
DEFAULT_CHARSET = "utf-8"
AUTH_USER_MODEL = "person.User"
#''''LOGING AUTHENTICATION'''
LOGIN_URL = "/auth/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
# PASSWORD_RESET_TIMEOUT_DAYS = 1
# https://docs.djangoproject.com/en/4.2/topics/auth/customizing/
AUTHENTICATION_BACKENDS = ["django.contrib.auth.backends.ModelBackend"]

"""REST_FRAMEWORK SETTINGS AND JWT-tokens"""
# https://pypi.org/project/djangorestframework-simplejwt/4.3.0/
# https://django-rest-framework-simplejwt.readthedocs.io/en/latest/stateless_user_authentication.html
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTStatelessUserAuthentication",
        "rest_framework.authentication.SessionAuthentication",  # This for works with sessions
        "rest_framework.authentication.TokenAuthentication",  # Options for API
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=int(JWT_ACCESS_TOKEN_LIFETIME_MINUTES)),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=int(JWT_REFRESH_TOKEN_LIFETIME_DAYS)),
    "SIGNING_KEY": SECRET_KEY,
}

# """DEBUG TOOLBAR - SERVER DAPHNE"""
DEBUG_TOOLBAR_CONFIG = {
    "SHOW_TOOLBAR_CALLBACK": lambda request: True,
}

# """EMAIL_BACKEND in down for a product"""
# https://docs.djangoproject.com/en/4.2/topics/email/#smtp-backend
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"  # console
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend" # IT's real email service
# EMAIL_BACKEND in down for a development

# https://docs.djangoproject.com/en/4.2/topics/email/#console-backend
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# https://docs.djangoproject.com/en/4.2/ref/settings/#default-from-email
# DEFAULT_FROM_EMAIL = f"smtp.{EMAIL_HOST_USER_}"

# https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-SMTP_HOST
# SMTP_HOST = 'smtp.example.com' # Замените на адрес вашего SMTP-сервера
# SMTP_HOST = 'mail.privateemail.com'
EMAIL_HOST = f"{SMTP_HOST}"
# https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-EMAIL_PORT
EMAIL_PORT = int(SMTP_PORT)  # 465
# https://docs.djangoproject.com/en/4.2/ref/settings/#email-host-user
EMAIL_HOST_USER = f"{SMTP_USER}"

# https://docs.djangoproject.com/en/4.2/ref/settings/#email-host-password
EMAIL_HOST_PASSWORD = f"{SMTP_PASS}"

# https://docs.djangoproject.com/en/4.2/ref/settings/#email-use-ssl
EMAIL_USE_SSL = True  # если порт 465

# https://docs.djangoproject.com/en/4.2/ref/settings/#email-use-tls
# EMAIL_USE_TLS = False
# EMAIL_USE_TLS = True  # если порт 587
# https://docs.djangoproject.com/en/4.2/ref/settings/#email-timeout
EMAIL_TIMEOUT = 60

# https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-EMAIL_USE_LOCALTIME
EMAIL_USE_LOCALTIME = True

# https://docs.djangoproject.com/en/4.2/ref/settings/#email-subject-prefix
# EMAIL_SUBJECT_PREFIX


# '''WEBPACK_LOADER'''
WEBPACK_LOADER = {
    "DEFAULT": {
        "CACHE": not DEBUG,
        # 'BUNDLE_DIR_NAME': '..\\frontend\\src\\bundles',
        "BUNDLE_DIR_NAME": "static",
        "STATS_FILE": os.path.join(
            BASE_DIR, "bundles/webpack-stats.json"
        ),

        "POLL_INTERVAL": 0.1,
        "TIMEOUT": None,
        "TEST": {
            # "NAME": "test_cloud",
        },
        "IGNORE": [
            # '.+\.map$'
            r".+\.hot-update.js",
            r".+\.map",
        ],
        "LOADER_CLASS": "webpack_loader.loader.WebpackLoader",
    }
}

# '''lOGGING'''
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
        },
    },
}

# """SWAGGER"""
# https://drf-yasg.readthedocs.io/en/stable/security.html#security-definitions

SWAGGER_USE_COMPAT_RENDERERS = False
SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Bearer": {"type": "apiKey", "name": "Authorization", "in": "header"}
    },
    "USE_SESSION_AUTH": False,
    "JSON_EDITOR": True,
    "VALIDATOR_URL": None,
    "exclude_namespaces": [],
}
SPECTACULAR_SETTINGS = {
    "TITLE": "Your API",
    "DESCRIPTION": "Your project description",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

# '''WAGTAIL'''
WAGTAIL_SITE_NAME = 'PERSON_PROFILE'
# Replace the search backend
WAGTAILSEARCH_BACKENDS = {
 'default': {
   'BACKEND': 'wagtail.search.backends.elasticsearch8',
   'INDEX': 'myapp'
 }
}
WAGTAILADMIN_BASE_URL = CORS_ALLOWED_ORIGINS[0]
