# Generated by Django 5.2.8 on 2025-11-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User"},
        ),
    ]
