# Generated by Django 5.2.8 on 2025-11-28 07:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0002_alter_user_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="patronymic",
        ),
        migrations.AddField(
            model_name="user",
            name="password_hash",
            field=models.CharField(
                default=0,
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(6),
                    django.core.validators.MaxLengthValidator(255),
                    django.core.validators.RegexValidator(
                        regex="[A-Za-z0-9-_%]{6,255)$"
                    ),
                ],
                verbose_name="password",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(regex="^(^$|A-Za-z]+$"),
                    django.core.validators.MaxLengthValidator(50),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
