# Generated by Django 5.2.8 on 2025-11-29 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0003_remove_user_patronymic_user_password_hash_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.DeleteModel(
            name="Role",
        ),
    ]
