# Generated by Django 5.2.8 on 2025-12-03 08:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0004_remove_user_role_delete_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessRolesModel",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
            ],
            options={
                "verbose_name": "Access roles",
                "db_table": "access_roles",
                "ordering": ("role", "element"),
            },
        ),
        migrations.CreateModel(
            name="BlackListModel",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[
                            django.core.validators.EmailValidator(),
                            django.core.validators.RegexValidator(
                                regex="(^[A-Za-z][A-Za-z_0-9-]{0,20}@[A-Za-z]{1,10}\\.[A-Za-z]{2,3})"
                            ),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Black List",
                "db_table": "person_blacklist",
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="BusinessElementModel",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The business element name",
                        max_length=120,
                        unique=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(120),
                            django.core.validators.MinLengthValidator(1),
                            django.core.validators.RegexValidator(
                                regex="^([A-Za-z0-9\\\"'%)(}{_ ]{1,120})$"
                            ),
                        ],
                        verbose_name="business element name",
                    ),
                ),
                (
                    "descriptions",
                    models.TextField(
                        blank=True,
                        help_text="The business element descriptions",
                        null=True,
                    ),
                ),
                (
                    "code",
                    models.TextField(
                        default="4ad5613e-89c3-4431-881f-f767fbf8736c",
                        help_text="The business element code",
                        max_length=50,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "business element",
                "verbose_name_plural": "business elements",
                "db_table": "business_element",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="RoleModel",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The role name. Min 3 & Max 50 characters long.",
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.MaxLengthValidator(50),
                            django.core.validators.RegexValidator(
                                regex="(^[A-Z][A-Za-z0-9_-]+$)"
                            ),
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="The description of the role. Max 150 characters long.",
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(150),
                            django.core.validators.RegexValidator(
                                regex="(^[A-Z][\\w_ -]+$)"
                            ),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "db_table": "role",
                "ordering": ("name",),
            },
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="user_is_acti_7f3bc2_idx",
        ),
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[
                    django.core.validators.EmailValidator(),
                    django.core.validators.RegexValidator(
                        regex="(^[A-Za-z][A-Za-z_0-9-]{0,20}@[A-Za-z]{1,10}\\.[A-Za-z]{2,3})"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(regex="(^$|[A-Za-z]+$)"),
                    django.core.validators.MaxLengthValidator(50),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(regex="(^$|[A-Za-z]+$)"),
                    django.core.validators.MaxLengthValidator(50),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password_hash",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(255),
                    django.core.validators.RegexValidator(
                        regex="[A-Za-z0-9-_)(%]{6,255}$"
                    ),
                ],
                verbose_name="password",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(regex="^(^$|[A-Za-z]+$)"),
                    django.core.validators.MaxLengthValidator(50),
                ],
            ),
        ),
        migrations.AddField(
            model_name="accessrolesmodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_roles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="accessrolesmodel",
            name="element",
            field=models.ForeignKey(
                blank=True,
                db_column="element_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_roles",
                to="person.businesselementmodel",
            ),
        ),
        migrations.AddField(
            model_name="accessrolesmodel",
            name="role",
            field=models.ForeignKey(
                db_column="role_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_roles",
                to="person.rolemodel",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="person.rolemodel",
            ),
            preserve_default=False,
        ),
    ]
