# Generated by Django 5.2.8 on 2025-11-29 03:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0004_remove_user_role_delete_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessElementModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The business element name",
                        max_length=120,
                        unique=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(120),
                            django.core.validators.MinLengthValidator(1),
                            django.core.validators.RegexValidator(
                                regex="^([A-Z][A-Za-z0-9_]{1,119})$"
                            ),
                        ],
                        verbose_name="business element name",
                    ),
                ),
                (
                    "descriptions",
                    models.TextField(
                        blank=True,
                        help_text="The business element descriptions",
                        null=True,
                    ),
                ),
                (
                    "code",
                    models.TextField(
                        default="5d1bfa2d-e763-44c3-9bf9-b2a3d6126b17",
                        help_text="The business element code",
                        max_length=50,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "business element",
                "verbose_name_plural": "business elements",
                "db_table": "business_element",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="RoleModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The role name. Min 3 & Max 50 characters long.",
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.MaxLengthValidator(50),
                            django.core.validators.RegexValidator(
                                regex="(^[A-Z][A-Za-z0-9_-]+$)"
                            ),
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="The description of the role. Max 150 characters long.",
                        null=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(150),
                            django.core.validators.RegexValidator(
                                regex="(^[A-Z][\\w_ -]+$)"
                            ),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "db_table": "role",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="AccessRolesModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "read_permission",
                    models.BooleanField(
                        db_column="read_permission",
                        default=False,
                        help_text="Read only own element",
                    ),
                ),
                (
                    "read_all_permission",
                    models.BooleanField(
                        db_column="read_all_permission",
                        default=False,
                        help_text="Read all user's elements",
                    ),
                ),
                (
                    "create_permission",
                    models.BooleanField(
                        db_column="create_permission",
                        default=False,
                        help_text="Create new element",
                    ),
                ),
                (
                    "update_permission",
                    models.BooleanField(
                        db_column="update_permission",
                        default=False,
                        help_text="Update only own element",
                    ),
                ),
                (
                    "update_all_permission",
                    models.BooleanField(
                        db_column="update_all_permission",
                        default=False,
                        help_text="Update all user's elements",
                    ),
                ),
                (
                    "delete_permission",
                    models.BooleanField(
                        db_column="delete_permission",
                        default=False,
                        help_text="Delete only own element",
                    ),
                ),
                (
                    "delete_all_permission",
                    models.BooleanField(
                        db_column="delete_all_permission",
                        default=False,
                        help_text="Delete all user's elements",
                    ),
                ),
                (
                    "element",
                    models.ForeignKey(
                        blank=True,
                        db_column="element_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_rules",
                        to="person.businesselementmodel",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        db_column="role_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_rules",
                        to="person.rolemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Access roles",
                "db_table": "access_roles",
                "ordering": ("role", "element"),
            },
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="person.rolemodel",
            ),
            preserve_default=False,
        ),
    ]
