# Generated by Django 5.2.8 on 2025-12-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "person",
            "0005_accessrolesmodel_blacklistmodel_businesselementmodel_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesselementmodel",
            name="code",
            field=models.TextField(
                default="2ae34a6d-2a37-489f-bd2a-4c9fcaa9129d",
                help_text="The business element code",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterModelTable(
            name="accessrolesmodel",
            table="person_access_roles",
        ),
        migrations.AlterModelTable(
            name="businesselementmodel",
            table="person_business_element",
        ),
        migrations.AlterModelTable(
            name="rolemodel",
            table="person_role",
        ),
    ]
