# Generated by Django 5.2.8 on 2025-11-29 07:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0005_businesselementmodel_rolemodel_accessrolesmodel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="usernane",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(regex="^(^$|A-Za-z]+$"),
                    django.core.validators.MaxLengthValidator(50),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="businesselementmodel",
            name="code",
            field=models.TextField(
                default="3d587d26-3bcd-4ddb-ad51-95f699e337ee",
                help_text="The business element code",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(regex="^(^$|A-Za-z]+$"),
                    django.core.validators.MaxLengthValidator(50),
                ],
            ),
        ),
    ]
