# Generated by Django 5.2.8 on 2025-11-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0006_user_usernane_alter_businesselementmodel_code_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="user_is_acti_7f3bc2_idx",
        ),
        migrations.AlterField(
            model_name="businesselementmodel",
            name="code",
            field=models.TextField(
                default="e9dfdd4c-1d07-4414-90b8-17aab84b2dd6",
                help_text="The business element code",
                max_length=50,
                unique=True,
            ),
        ),
    ]
