# Generated by Django 5.2.8 on 2025-11-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0007_remove_user_user_is_acti_7f3bc2_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesselementmodel",
            name="code",
            field=models.TextField(
                default="fa1312a5-141e-4c34-82f8-748a8063e3cc",
                help_text="The business element code",
                max_length=50,
                unique=True,
            ),
        ),
    ]
