# Generated by Django 5.2.8 on 2025-11-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0008_alter_businesselementmodel_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesselementmodel",
            name="code",
            field=models.TextField(
                default="fa2596a8-954f-42e7-95bf-3b650a875402",
                help_text="The business element code",
                max_length=50,
                unique=True,
            ),
        ),
    ]
