# Generated by Django 5.2.8 on 2025-11-29 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0009_alter_businesselementmodel_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="usernane",
        ),
        migrations.AlterField(
            model_name="businesselementmodel",
            name="code",
            field=models.TextField(
                default="6550741d-3c1b-4508-ab69-e2c447373d66",
                help_text="The business element code",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(regex="^(^$|A-Za-z]+$"),
                    django.core.validators.MaxLengthValidator(50),
                ],
            ),
        ),
    ]
