# Generated by Django 5.2.8 on 2025-11-29 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "person",
            "0010_remove_user_usernane_alter_businesselementmodel_code_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesselementmodel",
            name="code",
            field=models.TextField(
                default="f046f7ae-ac76-4b73-87c0-41bbb2340c12",
                help_text="The business element code",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password_hash",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(255),
                    django.core.validators.RegexValidator(
                        regex="[A-Za-z0-9-_%]{6,255)$"
                    ),
                ],
                verbose_name="password",
            ),
        ),
    ]
