# Generated by Django 5.2.8 on 2025-11-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0011_alter_businesselementmodel_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesselementmodel",
            name="code",
            field=models.TextField(
                default="0b57537f-1f92-43fe-84b1-5f00a88c8a8d",
                help_text="The business element code",
                max_length=50,
                unique=True,
            ),
        ),
    ]
