# Generated by Django 5.2.8 on 2025-11-29 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0012_alter_businesselementmodel_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesselementmodel",
            name="code",
            field=models.TextField(
                default="92276f75-ead2-4999-8c80-aa2558a58dc9",
                help_text="The business element code",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(regex="(^$|A-Za-z]+$"),
                    django.core.validators.MaxLengthValidator(50),
                ],
            ),
        ),
    ]
