# Generated by Django 5.2.8 on 2025-11-29 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0013_alter_businesselementmodel_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesselementmodel",
            name="code",
            field=models.TextField(
                default="b5dd141e-95bf-4e63-a70f-94d3fcfd23f5",
                help_text="The business element code",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(regex="(^$|[A-Za-z]+$"),
                    django.core.validators.MaxLengthValidator(50),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(regex="(^$|[A-Za-z]+$"),
                    django.core.validators.MaxLengthValidator(50),
                ],
            ),
        ),
    ]
