# Generated by Django 5.2.8 on 2025-11-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0014_alter_businesselementmodel_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesselementmodel",
            name="code",
            field=models.TextField(
                default="6eb049ed-b52b-4cdd-926a-0c28026ced8e",
                help_text="The business element code",
                max_length=50,
                unique=True,
            ),
        ),
    ]
