# Generated by Django 5.2.8 on 2025-11-29 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0015_alter_businesselementmodel_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesselementmodel",
            name="code",
            field=models.TextField(
                default="a04d38b5-9dbb-44e0-b5f7-4ced19c16966",
                help_text="The business element code",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password_hash",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(255),
                    django.core.validators.RegexValidator(
                        regex="[A-Za-z0-9-_%]{6,255}$"
                    ),
                ],
                verbose_name="password",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(regex="^(^$|[A-Za-z]+$)"),
                    django.core.validators.MaxLengthValidator(50),
                ],
            ),
        ),
    ]
