# Generated by Django 5.2.8 on 2025-11-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0016_alter_businesselementmodel_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesselementmodel",
            name="code",
            field=models.TextField(
                default="793e1cf9-aa04-4236-816c-2d2f68e40f48",
                help_text="The business element code",
                max_length=50,
                unique=True,
            ),
        ),
    ]
