# Generated by Django 5.2.8 on 2025-11-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0017_alter_businesselementmodel_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesselementmodel",
            name="code",
            field=models.TextField(
                default="8e27799f-f407-4c2a-bdf9-4043e88d0a46",
                help_text="The business element code",
                max_length=50,
                unique=True,
            ),
        ),
    ]
