# Generated by Django 5.2.8 on 2025-11-30 05:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0018_alter_businesselementmodel_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesselementmodel",
            name="code",
            field=models.TextField(
                default="75c01b4d-d8cb-4c67-8c0e-ce221acfc96e",
                help_text="The business element code",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
    ]
