# Generated by Django 5.2.8 on 2025-11-30 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0019_alter_businesselementmodel_code_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesselementmodel",
            name="code",
            field=models.TextField(
                default="bf00a3a8-021f-4f56-bb8a-a805f6de9a7a",
                help_text="The business element code",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[
                    django.core.validators.EmailValidator(),
                    django.core.validators.RegexValidator(
                        regex="(^[A-Za-z][A-Za-z_0-9-]{0,20}@[A-Za-z]{1,10}\\.[A-Za-z]{2,3})"
                    ),
                ],
            ),
        ),
    ]
