# Generated by Django 5.2.8 on 2025-11-30 06:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0020_alter_businesselementmodel_code_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesselementmodel",
            name="code",
            field=models.TextField(
                default="5d3328c8-f6aa-43d1-869d-00571c324026",
                help_text="The business element code",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password_hash",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(255),
                    django.core.validators.RegexValidator(
                        regex="[A-Za-z0-9-_)(%]{6,255}$"
                    ),
                ],
                verbose_name="password",
            ),
        ),
    ]
