# Generated by Django 5.2.8 on 2025-11-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0021_alter_businesselementmodel_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesselementmodel",
            name="code",
            field=models.TextField(
                default="5316a856-342f-4bc6-aeff-7eb5374e1b03",
                help_text="The business element code",
                max_length=50,
                unique=True,
            ),
        ),
    ]
