# Generated by Django 5.2.8 on 2025-11-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0022_alter_businesselementmodel_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesselementmodel",
            name="code",
            field=models.TextField(
                default="1a0bbd0c-8ad3-4008-b8a6-f3ea7b14fa35",
                help_text="The business element code",
                max_length=50,
                unique=True,
            ),
        ),
    ]
