# Generated by Django 5.2.8 on 2025-11-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0023_alter_businesselementmodel_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesselementmodel",
            name="code",
            field=models.TextField(
                default="3b4f3f93-15d6-4962-8434-5845462a32db",
                help_text="The business element code",
                max_length=50,
                unique=True,
            ),
        ),
    ]
