# Generated by Django 5.2.8 on 2025-11-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0024_alter_businesselementmodel_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesselementmodel",
            name="code",
            field=models.TextField(
                default="669cbc7d-e011-4c6e-b37a-356cc298d234",
                help_text="The business element code",
                max_length=50,
                unique=True,
            ),
        ),
    ]
