# Generated by Django 5.2.8 on 2025-11-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0025_alter_businesselementmodel_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="businesselementmodel",
            name="code",
            field=models.TextField(
                default="361e816b-cb07-4343-9ab9-c4a06be0cd09",
                help_text="The business element code",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
