# Generated by Django 5.2.8 on 2025-12-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0026_user_is_admin_alter_businesselementmodel_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accessrolesmodel",
            name="create_permission",
        ),
        migrations.RemoveField(
            model_name="accessrolesmodel",
            name="delete_all_permission",
        ),
        migrations.RemoveField(
            model_name="accessrolesmodel",
            name="delete_permission",
        ),
        migrations.RemoveField(
            model_name="accessrolesmodel",
            name="read_all_permission",
        ),
        migrations.RemoveField(
            model_name="accessrolesmodel",
            name="read_permission",
        ),
        migrations.RemoveField(
            model_name="accessrolesmodel",
            name="update_all_permission",
        ),
        migrations.RemoveField(
            model_name="accessrolesmodel",
            name="update_permission",
        ),
        migrations.AlterField(
            model_name="businesselementmodel",
            name="code",
            field=models.TextField(
                default="e8736fa9-4dd0-4248-a1a0-9944915cb1fc",
                help_text="The business element code",
                max_length=50,
                unique=True,
            ),
        ),
    ]
