# Generated by Django 5.2.8 on 2025-12-01 08:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0027_remove_accessrolesmodel_create_permission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrolesmodel",
            name="id",
            field=models.CharField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="businesselementmodel",
            name="code",
            field=models.TextField(
                default="894b0b25-3f94-4995-b477-5d50eab72ea2",
                help_text="The business element code",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="businesselementmodel",
            name="id",
            field=models.CharField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="rolemodel",
            name="id",
            field=models.CharField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
