# Generated by Django 5.2.8 on 2025-12-02 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0028_alter_accessrolesmodel_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesselementmodel",
            name="code",
            field=models.TextField(
                default="a6e67bb4-ee2b-44dc-ace3-0d96a099d8f9",
                help_text="The business element code",
                max_length=50,
                unique=True,
            ),
        ),
    ]
