# Generated by Django 5.2.8 on 2025-12-02 03:34

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("person", "0029_alter_businesselementmodel_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlackListModel",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created_at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[
                            django.core.validators.EmailValidator(),
                            django.core.validators.RegexValidator(
                                regex="(^[A-Za-z][A-Za-z_0-9-]{0,20}@[A-Za-z]{1,10}\\.[A-Za-z]{2,3})"
                            ),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Black List",
                "db_table": "person_blacklist",
                "ordering": ["email"],
            },
        ),
        migrations.AlterField(
            model_name="businesselementmodel",
            name="code",
            field=models.TextField(
                default="af80f7dd-60d9-492d-86d6-8f77c59a55fe",
                help_text="The business element code",
                max_length=50,
                unique=True,
            ),
        ),
    ]
